project:
  type: book

book:
  title: "Flutter Notes"
  author: "Kittipos"
  date: today
  repo-url: https://github.com/Lightbridge-KS/flutter-notes
  site-url: https://flutter-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Dart Basic
      chapters: 
        - "content/dart-basic/dart-convention.qmd"
        - "content/dart-basic/dart-variable.qmd"
        - "content/dart-howto/dart-sort.qmd"
        - "content/dart-basic/dart-types.qmd"
        - "content/dart-basic/dart-types-generic.qmd"
        - "content/dart-basic/dart-ctr-flow.qmd"
        - "content/dart-basic/dart-loop-collection.qmd"
        - "content/dart-basic/dart-fn.qmd"
        - "content/dart-basic/dart-lib-import.qmd"
        - "content/dart-basic/dart-pkg-org.qmd"
        - "content/dart-basic/dart-pkg-local.qmd"
        - "content/dart-basic/dart-pkg-app.qmd"
        - "content/dart-basic/dart-lib-org.qmd"
        - "content/dart-basic/dart-string.qmd"
    - part: OOP
      chapters: 
        - "content/dart-basic/dart-oop.qmd" 
        - "content/dart-oop/dart-class-init.qmd"
        - "content/dart-basic/dart-enum.qmd"
        - "content/dart-basic/dart-mixin.qmd" 
        - "content/dart-oop/dart-const-vs-nonconst.qmd"
        - "content/dart-oop/dart-factory.qmd"
        - "content/dart-oop/dart-factory-json.qmd"
        - "content/dart-oop/dart-interface-abs.qmd"
        - "content/dart-oop/dart-sealed-class.qmd"
    - part: Async
      chapters: 
        - "content/dart-async/dart-async.qmd"
        - "content/dart-async/dart-stream.qmd"
    - part: Logging
      chapters: 
        - "content/flutter-logging/logging-vs-exception.qmd"
        - "content/flutter-logging/logging-01-intro.qmd"
        - "content/flutter-logging/logging-02-app.qmd"
        - "content/flutter-logging/logging-03-file.qmd"
    - part: I/O
      chapters: 
        - "content/dart-json/dart-json-basic.qmd"
        - "content/dart-json/dart-json-serializable.qmd"
        - "content/dart-http/http-get.qmd"
        - "content/dart-http/http-post.qmd"
    - part: Config
      chapters: 
        - "content/dart-env/dart-env-var.qmd"
        - "content/dart-env/dart-env-dart-define.qmd"
        - "content/dart-env/dart-vm-mode.qmd"
    - part: Dart Advanced 
      chapters: 
        - "content/dart-basic/dart-logging.qmd"
        - "content/dart-basic/dart-logging-serious.qmd"
    - part: Dart Misc
      chapters: 
        - "content/dart-misc/dart-final-vs-const.qmd"
        - "content/dart-misc/dart-as-cast.md"
        - "content/dart-misc/dart-spread-operator.qmd"
        - "content/dart-misc/dart-null-guide.qmd"
        - "content/dart-misc/dart-null-from-api.qmd"
    - part: Dart Package
      chapters: 
        - "content/dart-pkg/dart-mustage.qmd"
    - part: Flutter Basic
      chapters: 
        - "content/flutter-basic/flutter-01-intro.qmd"
        - "content/flutter-basic/flutter-02-structure.qmd"
        - "content/flutter-basic/flutter-lib-structure.qmd"
        - "content/flutter-basic/flutter-03-widgets.qmd"
        - "content/flutter-basic/flutter-arg-parse.qmd"
    - part: Flutter Concept
      chapters: 
        - "content/flutter-concept/flutter-controller.qmd"
    - part: Error Handling
      chapters: 
        - "content/flutter-error/flutter-error-design.md"
    - part: Flutter State
      chapters: 
        - "content/flutter-state/state-basic-counter.qmd"
        - "content/flutter-state/state-provider-counter.qmd"
        - "content/flutter-state/riverpod.qmd"
        - "content/flutter-state/state-riverpod-counter.qmd"
        - "content/flutter-state/state-riverpod-counter-concept.qmd"
        - "content/flutter-state/state-riverpod-mvvm.qmd"
    - part: Image
      chapters: 
        - "content/flutter-image/flutter-img.qmd"
        - "content/flutter-image/flutter-img-byte-vs-file.qmd"
        - "content/flutter-image/flutter-img-base64-wf.qmd"
    - part: Test
      chapters: 
        - "content/unittest/test-basic.qmd"
        - "content/unittest/mockito-basic.qmd"
    - part: Deploy
      chapters: 
        - "content/deploy/deploy-localhost.qmd"
    # - part: "Example"
    #   chapters: 
    #     - "content/some_example.qmd"


bibliography: references.bib

format:
  html:
    theme:
      light:
      - cosmo
      dark: 
      - darkly
    toc-depth: 4

freeze: auto